<?php

namespace Hotflo\ORBundle\Repository;
use Doctrine\DBAL\Types\DateTimeType;
use Hotflo\ORBundle\Entity\Anesthetist;

/**
 * AnesthetistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnesthetistRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get a anesthetist's sessions for a given timeslot.
     *
     * @param Anesthetist $anesthetist
     * @param \DateTime $startTime
     * @param \DateTime $endTime
     * @return null|array
     */
    public function getAnesthetistSessionForTimeslot(Anesthetist $anesthetist, \DateTime $startTime, \DateTime $endTime)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('s')
            ->distinct()
            ->from('HotfloORBundle:Session', 's')
            ->join('s.anesthetists', 'anesthetist')
            ->where('anesthetist = :anesthetist')
            ->andWhere($qb->expr()->between('s.startTime', ':startTime', ':endTime'))
            ->orWhere($qb->expr()->between('s.endTime', ':startTime', ':endTime'))
            ->setParameter('anesthetist', $anesthetist)
            ->setParameter('startTime', $startTime, DateTimeType::DATETIME)
            ->setParameter('endTime', $endTime, DateTimeType::DATETIME);

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
