<?php

namespace Hotflo\ORBundle\Repository;

/**
 * OperatingRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatingRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
