<?php

namespace Hotflo\ORBundle\Repository;
use Doctrine\DBAL\Types\DateTimeType;
use Hotflo\ORBundle\Entity\Specialist;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get a specialist's session for a given timeslot.
     *
     * @param Specialist $specialist
     * @param \DateTime $startTime
     * @param \DateTime $endTime
     * @return null|array
     */
    public function getSpecialistSessionForTimeslot(Specialist $specialist, \DateTime $startTime, \DateTime $endTime)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('s')
            ->distinct()
            ->from('HotfloORBundle:Session', 's')
            ->join('s.specialist', 'specialist')
            ->where('s.specialist = :specialist')
            ->andWhere($qb->expr()->between('s.startTime', ':startTime', ':endTime'))
            ->orWhere($qb->expr()->between('s.endTime', ':startTime', ':endTime'))
            ->orWhere($qb->expr()->between(':startTime', 's.startTime', 's.endTime'))
            ->orWhere($qb->expr()->between(':endTime', 's.startTime', 's.endTime'))
            ->setParameter('specialist', $specialist)
            ->setParameter('startTime', $startTime, DateTimeType::DATETIME)
            ->setParameter('endTime', $endTime, DateTimeType::DATETIME);

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
