<?php

namespace Hotflo\ORBundle\Repository;

/**
 * SpecialismRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialismRepository extends \Doctrine\ORM\EntityRepository
{
}
