<?php

namespace Hotflo\ORBundle\Repository;
use Doctrine\DBAL\Types\DateTimeType;
use Hotflo\ORBundle\Entity\Specialist;

/**
 * SpecialistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialistRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get specialist sessions between given dates
     *
     * @param Specialist $specialist
     * @param $startDate
     * @param $endDate
     * @return array
     */
    public function getSpecialistSessionsBetweenDates(Specialist $specialist, \DateTime $startDate, \DateTime $endDate)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('s')
            ->distinct()
            ->from('HotfloORBundle:Session', 's')
            ->join('s.specialist', 'specialist')
            ->where('s.specialist = :specialist')
            ->andWhere($qb->expr()->between('s.startTime', ':startDate', ':endDate'))
            ->setParameter('specialist', $specialist)
            ->setParameter('startDate', $startDate, DateTimeType::DATETIME)
            ->setParameter('endDate', $endDate, DateTimeType::DATETIME);

            $result = $qb->getQuery()->getResult();

        return $result;
    }
}
