Hotflo\ORBundle\Entity\Anesthetist:
    type: entity
    table: null
    repositoryClass: Hotflo\ORBundle\Repository\AnesthetistRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        gender:
            type: string
            length: '10'
        dob:
            type: date
        availabilityPerWeek:
            type: integer
            column: availability_per_week

    manyToOne:
        hospital:
            targetEntity: Hotflo\ORBundle\Entity\Hospital
            inversedBy: anesthetists
            joinColumn:
                name: hospital_id
                referencedColumnName: id

    manyToMany:
        sessions:
            targetEntity: Hotflo\ORBundle\Entity\Session
            mappedBy: anesthetists

    lifecycleCallbacks: {  }
